server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:80
    gateway:
      routes:
        - id: user-service
          uri: lb://userservice # loadBalance 负载均衡
          predicates: # 路由断言
            - Path=/user/**   # 路径断言， 判断是否由user开头
        - id: order-service
          uri: lb://orderservice
          predicates: #
            - Path=/order/**
            - Before=2031-01-20T17:42:47.789-07:00[America/Denver]
          filters:
          - AddRequestHeader=Truth, hellokasjdfas d! # 针对某个服务的过滤器
      default-filters:
        - AddRequestHeader=Truth, asdfkaksdfj! # 默认过滤器，所有路由生效
